server:
    port: 8080
spring:
  application:
    name: dojo-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
            auto-commit: false
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true